name: Audiologger

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
    - name: Set Timezone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "Europe/Amsterdam"

    - name: Install ffmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Record audio
      run: |
        #!/bin/sh
        # wait for top of the hour
        while [ "$(date +%M)" != "00" ]; do
          sleep 1
        done
        FILENAME=$(date +%Y-%m-%d_%H).mp3
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        ffmpeg -y -i https://icecast.zuidwestfm.nl/zuidwest.mp3 -t 3600 -c copy $FILENAME
        echo "::set-output name=filename::$FILENAME"
      id: record_step

    - name: Upload recorded audio as artifact
      uses: actions/upload-artifact@v3
      with:
        name: recorded_audio
        path: ${{ env.FILENAME }}

  upload:
    needs: record
    runs-on: ubuntu-latest

    steps:
    - name: Download recorded audio artifact
      uses: actions/download-artifact@v3
      with:
        name: recorded_audio

    - name: Install backblaze-b2
      run: sudo apt-get update && sudo apt-get install -y backblaze-b2

    - name: Configure B2 CLI
      run: |
        backblaze-b2 authorize-account ${{ secrets.B2_KEY_ID }} ${{ secrets.B2_APPLICATION_KEY }}

    - name: Upload file to Backblaze B2
      env:
        B2_BUCKET_NAME: audiologger
      run: |
        FILENAME=${{ needs.record.outputs.filename }}
        backblaze-b2 upload-file $B2_BUCKET_NAME $FILENAME $FILENAME
